#!/bin/bash
# ============================================================
#  Rathole RDP Server Deploy Script
#  by JPaasovaara - MIT License
#
#  Installs rathole server on a Linux VPS and configures it
#  to accept reverse tunnel connections from Windows clients.
#
#  Usage: sudo bash deploy.sh
#  Or with slots file: sudo bash deploy.sh --slots /path/to/slots.txt
# ============================================================

set -e

# --- Configuration ---
RATHOLE_VERSION="0.5.0"
INSTALL_DIR="/opt/rathole"
CONFIG_FILE="$INSTALL_DIR/server.toml"
SERVICE_NAME="rathole"
BIND_PORT=2333  # Control channel port (clients connect here)

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# --- Functions ---
info()  { echo -e "${CYAN}[i]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
fail()  { echo -e "${RED}[X]${NC} $1"; }

check_root() {
    if [ "$EUID" -ne 0 ]; then
        fail "This script must be run as root (use sudo)"
        exit 1
    fi
}

detect_arch() {
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64)  RATHOLE_ARCH="x86_64-unknown-linux-gnu" ;;
        aarch64) RATHOLE_ARCH="aarch64-unknown-linux-gnu" ;;
        armv7l)  RATHOLE_ARCH="armv7-unknown-linux-gnueabihf" ;;
        *)
            fail "Unsupported architecture: $ARCH"
            exit 1
            ;;
    esac
    ok "Architecture: $ARCH ($RATHOLE_ARCH)"
}

download_rathole() {
    info "Downloading rathole v${RATHOLE_VERSION}..."
    
    DOWNLOAD_URL="https://github.com/rapiz1/rathole/releases/download/v${RATHOLE_VERSION}/rathole-${RATHOLE_ARCH}.zip"
    TMP_DIR=$(mktemp -d)
    
    if ! wget -q "$DOWNLOAD_URL" -O "$TMP_DIR/rathole.zip"; then
        fail "Download failed from: $DOWNLOAD_URL"
        exit 1
    fi
    
    unzip -q "$TMP_DIR/rathole.zip" -d "$TMP_DIR"
    
    mkdir -p "$INSTALL_DIR"
    cp "$TMP_DIR/rathole" "$INSTALL_DIR/rathole"
    chmod +x "$INSTALL_DIR/rathole"
    rm -rf "$TMP_DIR"
    
    ok "Rathole v${RATHOLE_VERSION} installed to $INSTALL_DIR/rathole"
}

generate_config_from_slots() {
    local slots_file="$1"
    
    info "Generating server config from slots file..."
    
    cat > "$CONFIG_FILE" << EOF
# Rathole RDP Server Configuration
# Generated by deploy.sh on $(date -Iseconds)
# Control channel: clients connect to port $BIND_PORT

[server]
bind_addr = "0.0.0.0:${BIND_PORT}"

[server.transport]
type = "noise"

[server.transport.noise]
local_private_key = "$(openssl rand -base64 32)"

EOF

    while IFS='|' read -r name port token address; do
        # Skip comments and empty lines
        [[ "$name" =~ ^#.*$ ]] && continue
        [[ -z "$name" ]] && continue
        
        cat >> "$CONFIG_FILE" << EOF
[server.services.${name}]
token = "${token}"
bind_addr = "0.0.0.0:${port}"

EOF
        ok "  Slot: ${name} -> port ${port} (${address})"
    done < "$slots_file"
    
    chmod 600 "$CONFIG_FILE"
    ok "Server config written to $CONFIG_FILE"
}

generate_config_interactive() {
    info "No slots file provided. Interactive setup..."
    echo ""
    echo "  How many RDP slots do you want to configure?"
    read -p "  Number of slots [1-20]: " num_slots
    
    if ! [[ "$num_slots" =~ ^[0-9]+$ ]] || [ "$num_slots" -lt 1 ] || [ "$num_slots" -gt 20 ]; then
        fail "Invalid number. Must be 1-20."
        exit 1
    fi
    
    cat > "$CONFIG_FILE" << EOF
# Rathole RDP Server Configuration
# Generated by deploy.sh on $(date -Iseconds)
# Control channel: clients connect to port $BIND_PORT

[server]
bind_addr = "0.0.0.0:${BIND_PORT}"

[server.transport]
type = "noise"

[server.transport.noise]
local_private_key = "$(openssl rand -base64 32)"

EOF

    local base_port=3389
    echo ""
    echo "  Generating $num_slots slot(s) starting at port $base_port..."
    echo ""
    
    for ((i=0; i<num_slots; i++)); do
        local port=$((base_port + i))
        local token=$(openssl rand -hex 32)
        local name="rdp$((i+1))"
        
        if [ $i -eq 0 ]; then
            read -p "  Name for slot 1 (port $port) [rdp1]: " custom_name
            name="${custom_name:-rdp1}"
        else
            read -p "  Name for slot $((i+1)) (port $port) [rdp$((i+1))]: " custom_name
            name="${custom_name:-rdp$((i+1))}"
        fi
        
        cat >> "$CONFIG_FILE" << EOF
[server.services.${name}]
token = "${token}"
bind_addr = "0.0.0.0:${port}"

EOF
        echo "  ${GREEN}${name}${NC} | port: ${port} | token: ${token}"
    done
    
    chmod 600 "$CONFIG_FILE"
    echo ""
    warn "SAVE THE TOKENS ABOVE! You need them for the client setup."
    echo ""
    ok "Server config written to $CONFIG_FILE"
}

setup_firewall() {
    info "Configuring firewall (ufw)..."
    
    # Get ports from config
    local ports=$(grep -oP 'bind_addr = "0.0.0.0:\K[0-9]+' "$CONFIG_FILE" | sort -u)
    
    for port in $ports; do
        if command -v ufw &> /dev/null; then
            ufw allow "$port/tcp" > /dev/null 2>&1
            ok "  Firewall: allowed TCP port $port"
        elif command -v firewall-cmd &> /dev/null; then
            firewall-cmd --permanent --add-port="$port/tcp" > /dev/null 2>&1
            ok "  Firewall: allowed TCP port $port"
        fi
    done
    
    if command -v ufw &> /dev/null; then
        ufw reload > /dev/null 2>&1
    elif command -v firewall-cmd &> /dev/null; then
        firewall-cmd --reload > /dev/null 2>&1
    else
        warn "  No firewall manager found. Ensure ports are open manually."
    fi
}

setup_fail2ban() {
    info "Configuring fail2ban for RDP ports..."
    
    if ! command -v fail2ban-client &> /dev/null; then
        warn "  fail2ban not installed. Installing..."
        apt-get update -qq && apt-get install -y -qq fail2ban > /dev/null 2>&1
    fi
    
    # Get RDP ports (not the control port)
    local rdp_ports=$(grep -oP 'bind_addr = "0.0.0.0:\K[0-9]+' "$CONFIG_FILE" | grep -v "^${BIND_PORT}$" | tr '\n' ',' | sed 's/,$//')
    
    cat > /etc/fail2ban/jail.d/rathole-rdp.conf << EOF
# Rathole RDP - Rate limit connections to RDP ports
# Generated by deploy.sh

[rathole-rdp]
enabled = true
filter = rathole-rdp
port = ${rdp_ports}
logpath = /var/log/rathole.log
maxretry = 5
findtime = 300
bantime = 3600
EOF

    cat > /etc/fail2ban/filter.d/rathole-rdp.conf << EOF
# Rathole RDP fail2ban filter
[Definition]
failregex = 
ignoreregex = 
EOF

    # For now, use iptables rate limiting as primary defense
    # fail2ban will be enhanced when rathole adds connection logging
    
    ok "  fail2ban configured (jail: rathole-rdp)"
}

setup_iptables_ratelimit() {
    info "Setting up iptables rate limiting..."
    
    local rdp_ports=$(grep -oP 'bind_addr = "0.0.0.0:\K[0-9]+' "$CONFIG_FILE" | grep -v "^${BIND_PORT}$")
    
    for port in $rdp_ports; do
        # Allow max 5 new connections per minute per source IP
        iptables -I INPUT -p tcp --dport "$port" -m state --state NEW -m recent --set --name "rdp_${port}"
        iptables -I INPUT -p tcp --dport "$port" -m state --state NEW -m recent --update --seconds 60 --hitcount 5 --name "rdp_${port}" -j DROP
        ok "  Rate limit: port $port (max 5 new conn/min per IP)"
    done
    
    # Save iptables rules
    if command -v netfilter-persistent &> /dev/null; then
        netfilter-persistent save > /dev/null 2>&1
    elif command -v iptables-save &> /dev/null; then
        iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
    fi
}

create_systemd_service() {
    info "Creating systemd service..."
    
    cat > /etc/systemd/system/${SERVICE_NAME}.service << EOF
[Unit]
Description=Rathole RDP Reverse Tunnel Server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/rathole ${CONFIG_FILE}
Restart=always
RestartSec=5
StandardOutput=append:/var/log/rathole.log
StandardError=append:/var/log/rathole.log

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/log/rathole.log
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    # Create log file
    touch /var/log/rathole.log
    
    # Setup log rotation
    cat > /etc/logrotate.d/rathole << EOF
/var/log/rathole.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    postrotate
        systemctl restart rathole > /dev/null 2>&1 || true
    endscript
}
EOF

    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME" > /dev/null 2>&1
    systemctl start "$SERVICE_NAME"
    
    ok "Service '$SERVICE_NAME' created and started"
}

verify_service() {
    info "Verifying service status..."
    sleep 2
    
    if systemctl is-active --quiet "$SERVICE_NAME"; then
        ok "Service is running"
        
        # Check listening ports
        local ports=$(ss -tlnp | grep rathole | awk '{print $4}' | grep -oP ':\K[0-9]+' | sort -n | tr '\n' ' ')
        ok "Listening on ports: $ports"
    else
        fail "Service failed to start!"
        echo ""
        journalctl -u "$SERVICE_NAME" --no-pager -n 20
        exit 1
    fi
}

show_summary() {
    echo ""
    echo "==========================================================="
    echo -e "  ${GREEN}RATHOLE RDP SERVER - INSTALLATION COMPLETE${NC}"
    echo "==========================================================="
    echo ""
    echo "  Server:  $(hostname -I | awk '{print $1}'):${BIND_PORT} (control channel)"
    echo "  Config:  $CONFIG_FILE"
    echo "  Service: systemctl {start|stop|restart|status} $SERVICE_NAME"
    echo "  Logs:    /var/log/rathole.log"
    echo ""
    echo "  Configured slots:"
    
    grep -oP '\[server\.services\.\K[^\]]+' "$CONFIG_FILE" | while read -r name; do
        local port=$(grep -A2 "\[server\.services\.${name}\]" "$CONFIG_FILE" | grep bind_addr | grep -oP ':\K[0-9]+')
        local token=$(grep -A2 "\[server\.services\.${name}\]" "$CONFIG_FILE" | grep token | grep -oP '"[^"]*"' | tr -d '"')
        echo "    $name -> port $port"
    done
    
    echo ""
    echo "  Security:"
    echo "    - Noise Protocol encryption (tunnel)"
    echo "    - iptables rate limiting (5 conn/min per IP)"
    echo "    - fail2ban (auto-ban after 5 failures)"
    echo ""
    echo "  Next: Run the client setup script on each Windows PC"
    echo "==========================================================="
}

# --- Main ---
echo "==========================================================="
echo "  Rathole RDP Server Deploy"
echo "  by JPaasovaara - MIT License"
echo "==========================================================="
echo ""

check_root
detect_arch

# Check for existing installation
if [ -f "$INSTALL_DIR/rathole" ]; then
    warn "Existing installation found at $INSTALL_DIR"
    read -p "  Overwrite? [y/N]: " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        info "Aborted."
        exit 0
    fi
    systemctl stop "$SERVICE_NAME" 2>/dev/null || true
fi

download_rathole

# Check for --slots argument
SLOTS_FILE=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --slots)
            SLOTS_FILE="$2"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

if [ -n "$SLOTS_FILE" ] && [ -f "$SLOTS_FILE" ]; then
    generate_config_from_slots "$SLOTS_FILE"
else
    generate_config_interactive
fi

setup_firewall
setup_iptables_ratelimit
setup_fail2ban
create_systemd_service
verify_service
show_summary
